#!/usr/local/bin/python

import sys, os, re, string;

from pygments import highlight
from pygments.lexers import (get_lexer_by_name, get_lexer_for_mimetype)
from pygments.lexers import guess_lexer
from pygments.formatters import (HtmlFormatter, get_formatter_by_name)
from pygments.util import ClassNotFound

print "Content-Type: application/xml"
print ""

query = os.environ["QUERY_STRING"]
code = ""

for line in sys.stdin:
    code = code + line.decode("utf8")

language = re.search("language=([^?&]+)", os.environ["QUERY_STRING"])
if language is None:
    language = ""
else:
    language = language.group(1)

formatname = re.search("formatter=([^?&]+)", os.environ["QUERY_STRING"])
if formatname is None:
    formatname = "html"
else:
    formatname = formatname.group(1)

if language == "":
    lexer = guess_lexer(code)
else:
    try:
        lexer = get_lexer_by_name(language)
    except ClassNotFound:
        lexer = ""

formatter = get_formatter_by_name(formatname)

try:
    result = highlight(code, lexer, formatter)
except AttributeError:
    sys.stderr.write("Failed to highlight code: lexer=" + lexer + " formatter=" + formatname + "\n")
    sys.stderr.write(code.encode("ascii","xmlcharrefreplace") + "\n")
    code = code.replace("&", "&amp;").replace("<", "&lt;").replace(">","&gt;")
    result = "<pre>" + code + "</pre>"

# Put it in the right namespace
result = "<div xmlns='http://www.w3.org/1999/xhtml'>" + result + "</div>"

print result.encode("ascii","xmlcharrefreplace")
