#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;

my $query_string = "";
my $post_body = "";
my $post_length = 0;

$query_string = $ENV{'QUERY_STRING'};

if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    $post_length = $ENV{'CONTENT_LENGTH'};
    read(STDIN, $post_body, $ENV{'CONTENT_LENGTH'});
}

my $temp = "/tmp/essay-validate.$$.xml";
my $err = "/tmp/essay-validate.$$.err";

$temp = "/tmp/essay-validate.xml";
$err = "/tmp/essay-validate.err";

open (F, ">$temp");
print F $post_body;
close (F);

print "Content-type: text/plain\n\n";

my $lib = "/MarkLogic/nwn/apache/lib";
my @cp = ();
opendir (DIR, $lib);
while (my $name = readdir(DIR)) {
    next if $name =~ /^\.\.?$/;
    next unless $name =~ /\.jar$/;
    push (@cp, "$lib/$name");
}
closedir (DIR);

my $cp = join(":", @cp);

my @results = ();
open (F, "java -cp $cp com.xmlcalabash.drivers.Main -isource=$temp /MarkLogic/nwn/apache/xpl/validate-essay.xpl 2>$err |");
while (<F>) {
    print STDERR $_;
    push (@results, $_);
}
close (F);

open (F, $err);
while (<F>) {
    chop;
    if (/^Error on/ or /^SEVERE:/) {
        print "<c:errors xmlns:c=\"http://www.w3.org/ns/xproc-step\">Calabash failed</c:errors>\n";
        exit 0;
    }
}
close (F);

while (@results) {
    print shift @results;
}

#unlink ($temp, $err);

exit 0;
