#!/usr/bin/perl -- # -*- Perl -*-

use strict;
use English;

my $query_string = "";
my $post_body = "";
my $post_length = 0;

$query_string = $ENV{'QUERY_STRING'};

if ($ENV{'REQUEST_METHOD'} eq 'POST') {
    $post_length = $ENV{'CONTENT_LENGTH'};
    read(STDIN, $post_body, $ENV{'CONTENT_LENGTH'});
}

my $temp = "/tmp/essay-validate.$$.xml";
my $err = "/tmp/essay-validate.$$.err";
open (F, ">$temp");
print F $post_body;
close (F);

print "Content-type: text/plain\n\n";

my @results = ();
open (F, "/Users/ndw/bin/calabash -isource=$temp /MarkLogic/nwn/apache/xpl/validate-essay.xpl 2>$err |");
while (<F>) {
    push (@results, $_);
}
close (F);

open (F, $err);
while (<F>) {
    chop;
    if (/^Error on/ or /^SEVERE:/) {
        print "<c:errors xmlns:c=\"http://www.w3.org/ns/xproc-step\">Calabash failed</c:errors>\n";
        exit 0;
    }
}
close (F);

while (@results) {
    print shift @results;
}

unlink ($temp, $err);

exit 0;
